### ISSUE TITLE
Ubuntu version upgrades QEMU too far

### ISSUE THREAD

**Issue by seeker25** [Wenzel/vagrant-xen-pyvmidbg#4]
Ubuntu version upgrades QEMU too far. Seemed to put me at 2.12, so when I try to run any of the libvirt examples, they fail. 

I downgraded to 2.8 (which was a pain, because the latest GLIBC has issues compiling it), but now I realize it's LOWER than 2.8 to run.

**Comment by Wenzel** [comment]
Hi,
You don't need to care about qemu version here, since you don't have to patch it.

This vagrant is for Xen, not KVM.

**Comment by seeker25** [comment]
Ahh my mistake Wenzel, I just noticed that now. Back to 2.12! Thank you.

**Comment by Wenzel** [comment]
I would recommend using the fedora vagrant image, it's much more up to date, and the one i am using to test it

**Comment by seeker25** [comment]
Got it, trying it now.

**Comment by seeker25** [comment]
It's a shame, I'm running this on Ubuntu 18.04 (host), I tried the Fedora version. It gets stuck on build vm with Packer for a while. I let it go last night, but when I tried to connect through Virtual Machine Manager, the win7 distro wasn't there. The Ubuntu version works no problem and installs pretty fast. 

Sorry the Ubuntu version works with KVM, not Xen. Xen seems to just freeze when you start up the VM.

**Comment by Wenzel** [comment]
So, why building the vm is super slow is because i'm using packer and packer doesn't have a plugin for Xen

So i'm using full emulation with qemu, and sometimes it's so slow that the build got stuck

**Comment by Wenzel** [comment]
I looked at the ubuntu playbook and it should be running Xen as well.

If you are sure that kvm is running then something got wrong in the playbook.

**Comment by Wenzel** [comment]
Also, the only vm being built here is Windows xp, not Windows 7

**Comment by seeker25** [comment]
Ahh I see, I think I'm going to give up on this. Xen doesn't want to play nice on my computer even if I try to install it directly on the host. It instantly crashes the host fedora VM. It's too bad, this looks great. 
Thanks for all your work.

**Comment by Wenzel** [comment]
hi,

It's really a shame that Xen causes you so much troubles.
I'm sad to hear that Vagrant didn't heleped either.

I had a quick chat on the Xen IRC, and they wanted to help if you could explain what happens on with your setup on the xen mailing list:
xen-users@lists.xenproject.org

Also, i plan to have KVM support for pyvmidbg by the end of september.
