### ISSUE TITLE
Requires Virt-manager as well

### ISSUE THREAD

**Issue by seeker25** [Wenzel/vagrant-xen-pyvmidbg#5]
Hey it's me again :D 

I'm running this on my intel machine, under requirements.. you need virt-manager. 

Just thought i'd put this up here.

**Comment by Wenzel** [comment]
Hey,

virt-manager is a GUI on top of libvirt,
I dont see how is it absolutely necessary for running Vagrant and the project ?

Can you add more details ?
Thanks.

**Comment by seeker25** [comment]
If I remember right one of those vagrant plugins requires it. I can't remember. I did do the list here, I had to install more stuff.

**Comment by Wenzel** [comment]
`vagrant-libvirt` requires libvirt headers (`libvirt-dev`) since it compiles some native modules.
this dependency is already listed.

I don't think virt-manager is a strong dependency here, so I'm going to clone this issue.

feel free to reopen it if you have more information.

Thanks
